version: "3.7" 
services:

  app:
    build:
      args:
        user: laravel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: phpdocker
    container_name: php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks: 
      - myNetwork

  server:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - myNetwork

  db:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel-api-restful
      MYSQL_USER: laravel
      MYSQL_ROOT_PASSWORD: 1qazxsw2
      MYSQL_PASSWORD: 1qazxsw2
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - myNetwork

networks: 
  myNetwork:
    driver: bridge